#!/bin/bash
 
# Copyright (c) 2013 Christopher Will<dev@cwill-dev.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of 
# this software and associated documentation files (the "Software, to deal in the 
# Software without restriction, including without limitation the rights to use, 
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the 
# Software, and to permit persons to whom the Software is furnished to do so, subject 
# to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#####################################################################################
#
# VIRTUALBOX
# Create snapshots of each installed VM, so rsync is able to backup the VirtualBox
# images incrementally
#
#####################################################################################


#####################################################################################
#
# EVENT HANDLER
#
#####################################################################################

function virtual_box_on_plugin_loaded() { 
	:	
}
function virtual_box_before_validation() {  	
	:
}
function virtual_box_after_validation() { 
	: 
}
# Create incremental snapshots before rsync starts its job
function virtual_box_before_process() {  
	create_snapshots
}
function virtual_box_on_process() { 
	: 
}
function virtual_box_after_process() { 
	: 
}
function virtual_box_before_restore_preparation() { 
	: 
}
function virtual_box_after_restore_preparation() { 
	: 
}
function virtual_box_on_finish() { 
	:
}
function virtual_box_on_failure() { 
	: 
}
function virtual_box_on_output() { 
	: 
}


#####################################################################################
#
# LOCAL FUNCTIONS
#
#####################################################################################

function create_snapshots() {
	output ""
	output "============================================================"
	output "= Plugin VirtualBox started"
	output "============================================================"
	output "> Creating VirtualBox snapshots"

	# Do snapshots for all home_users
	for ((vb_index=0;vb_index<${#home_users[@]};vb_index++)); do

		output "> > User: ${home_users[vb_index]}"

		# Get all installed VMs
		vms=$(su -c "VBoxManage list vms | sed -E 's/^\"(.*)\".*/\1/g'" -s /bin/sh ${home_users[vb_index]})

		# Create new snapshot of each
		for vm_name in $vms; do 
			output "> > > Processing ${vm_name}.."
			$(su -c "VBoxManage snapshot ${vm_name} take ${date} --description \"Generated by myback automatically at {$date}\" --pause" -s /bin/sh ${home_users[vb_index]})
			output "> > > [DONE] ${vm_name}"
		done
		
	done

	output "> [DONE] Creating VirtualBox snapshots"
	output "============================================================"
	output "= Plugin VirtualBox finished"
	output "============================================================"
	output ""
}